id = "julia"
name = "Julia"
description = "Julia support."
version = "0.1.0"
schema_version = 1
authors = ["Paul Berg <paul@plutojl.org>"]
repository = "https://github.com/Pangoraw/zed-julia"

[grammars.julia]
repository = "https://github.com/tree-sitter/tree-sitter-julia"
commit = "0a80d33aca49dd257625ab25ef3a506e2b99a554"

[language_servers.julia]
languages = ["Julia"]
name = "LanguageServer.jl"
