id = "julia"
name = "Julia"
description = "Julia support."
version = "0.1.0"
schema_version = 1
authors = ["Paul Berg <paul@plutojl.org>"]
repository = "https://github.com/Pangoraw/zed-julia"

[grammars.julia]
repository = "https://github.com/tree-sitter/tree-sitter-julia"
commit = "acd5ca12cc278df7960629c2429a096c7ac4bbea"

[language_servers.julia]
languages = ["Julia"]
name = "LanguageServer.jl"
